import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateTransactionReport(
  transactions: any[]
) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(31, 94, 59);
  doc.text(
    "SHREE MAHANTESHWARA TRADERS",
    14,
    20
  );

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(
    "Agricultural Commission Report",
    14,
    30
  );

  // Table
  autoTable(doc, {
    startY: 40,

    head: [[
      "Farmer",
      "Crop",
      "Qty",
      "Rate",
      "Commission",
      "Net Amount",
    ]],

    body: transactions.map((t) => [
      t.farmers?.name || "",
      t.crop_name || "",
      t.quantity || 0,
      `₹ ${t.rate || 0}`,
      `₹ ${t.commission_amount || 0}`,
      `₹ ${t.net_amount || 0}`,
    ]),

    styles: {
      fontSize: 10,
    },

    headStyles: {
      fillColor: [31, 94, 59],
    },
  });

  // Footer
  doc.setFontSize(10);
  doc.text(
    "Generated by SHREE MAHANTESHWARA TRADERS ERP",
    14,
    doc.internal.pageSize.height - 10
  );

  // Download PDF
  doc.save("transactions-report.pdf");
}